apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: clusterroles-spawner-rules
parameters:
- name: SPAWNER_NAMESPACE
  value: ""
  required: true
- name: SPAWNER_APPLICATION
  value: ""
  required: true
objects:
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cluster-admin-${SPAWNER_APPLICATION}-${SPAWNER_NAMESPACE}-hub
    labels:
      app: ${SPAWNER_APPLICATION}-${SPAWNER_NAMESPACE}
      spawner: learning-portal
  subjects:
  - kind: ServiceAccount
    name: ${SPAWNER_APPLICATION}-${SPAWNER_NAMESPACE}-hub
    namespace: ${SPAWNER_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    labels:
      app: ${SPAWNER_APPLICATION}-${SPAWNER_NAMESPACE}
      spawner: learning-portal
    name: ${SPAWNER_APPLICATION}-${SPAWNER_NAMESPACE}-spawner-rules
  rules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - ""
    - security.openshift.io
    resources:
    - securitycontextconstraints
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - ""
    - authorization.openshift.io
    - rbac.authorization.k8s.io
    resources:
    - clusterroles
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - ""
    - authorization.openshift.io
    - rbac.authorization.k8s.io
    resources:
    - clusterrolebindings
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
